name: Cypress Starter - Run Sample Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Linting
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
          
      - name: Lint Project
        run: |
          yarn install --frozen-lockfile
          yarn lint
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Run Sample Tests
      run: yarn run cy:run
      
    - name: Merge Reports 
      run: yarn run cy:merge-reports
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "cypress/results/combined-report.xml"
        check_name: "Cypress Results"
